###
POST http://127.0.0.1:8080/auth/oauth/token?grant_type=password&account_name=admin&password=123456
Content-Type: application/json
# client: test:test123
Authorization: Basic dGVzdDp0ZXN0MTIz

###
POST http://127.0.0.1:8080/auth/oauth/token
Content-Type: application/x-www-form-urlencoded
# client: test:test123
Authorization: Basic ZGV2OnRlc3QxMjM=

grant_type=password&account_name=root&password=123456&remember_me=true&captcha=2&checkKey=1601396062575

###
POST http://127.0.0.1:8080/auth/oauth/token?grant_type=client_credentials&scope=read
Content-Type: application/json
# client: test:test123
Authorization: Basic dGVzdDp0ZXN0MTIz

###
GET http://127.0.0.1:8080/auth/pub/captcha/12345678
Content-Type: application/json

###
