server:
  port: 8080
  servlet:
    context-path: /mdm
spring:
  profiles:
    include: redis,mybatis,web
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://dev.entdiy.com:3306/entdiy-mdm?useUnicode=true&characterEncoding=utf-8
    username: root
  redis:
    host: 103.120.227.84
    port: 6379
    database: 5
    password: xuemeiredis
security:
  ignore-urls:
    - /rest/data/ignore
    - /rpc/**/*
  #acl-mappings:
    #https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-Configuration-Binding
    #"[/rest/company/**/*]": "hasAnyRole('ROLE_COMPANY_USER','ROLE_COMPANY_ADMIN') or #oauth2.isClient()"
    #"[/rest/**/*]": "hasAnyRole('ROLE_COMPANY_USER') or #oauth2.isClient()"
  oauth2:
    client:
      client-id: xuemei-management
      client-secret: 123456
mybatis-plus:
  typeEnumsPackage: com.xuemei.common;com.xuemei.mdm
  configuration:
    cache-enabled: false