server:
  port: 8080
  servlet:
    context-path: /mdm
spring:
  profiles:
    include: server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql.entdiy.com:3306/entdiy-mdm?useUnicode=true&characterEncoding=utf-8
    username: root
    password: mysqlP@sswd123
  redis:
    host: redis.entdiy.com
    port: 6379
    database: 1
    password: redisP@sswd123
swagger: # Based on https://gitee.com/Wilson-He/swagger2-spring-boot-starter
  dockets:
    docket-admin:
      base-package: com.entdiy.mdm.controller.admin
      group-name: Admin管理接口
      api-info:
        contact:
          name: Li Xia
          email: xautlx@hotmail.com
        version: ${app.context.buildVersion}
        title: Admin API for ${app.context.systemName}
      global-parameters:
        - name: Authorization
          description: Bearer {Access Token}
          param-type: header
    docket-app:
      base-package: com.entdiy.mdm.controller.app
      group-name: APP应用接口
      api-info:
        contact:
          name: Li Xia
          email: xautlx@hotmail.com
        version: ${app.context.buildVersion}
        title: APP API for ${app.context.systemName}
      global-parameters:
        - name: Authorization
          description: Bearer {Access Token}
          param-type: header
    docket-rpc:
      base-package: com.entdiy.mdm.controller.rpc
      group-name: RPC内部接口
      api-info:
        contact:
          name: Li Xia
          email: xautlx@hotmail.com
        version: ${app.context.buildVersion}
        title: RPC API for ${app.context.systemName}
      global-parameters:
        - name: Authorization
          description: Bearer {Access Token}
          param-type: header
security:
  ignore-urls:
    - /rest/data/ignore
    - /rpc/**/*
  #acl-mappings:
    #https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-Configuration-Binding
    #"[/rest/company/**/*]": "hasAnyRole('ROLE_COMPANY_USER','ROLE_COMPANY_ADMIN') or #oauth2.isClient()"
    #"[/rest/**/*]": "hasAnyRole('ROLE_COMPANY_USER') or #oauth2.isClient()"
  oauth2:
    client:
      client-id: entdiy-mdm
      client-secret: 123456