server:
  port: 8080
  servlet:
    context-path: /mdm
spring:
  profiles:
    include: server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql.entdiy.com:3306/entdiy-mdm?useUnicode=true&characterEncoding=utf-8
    username: root
    password: mysqlP@sswd123
  redis:
    host: redis.entdiy.com
    port: 6379
    database: 1
    password: redisP@sswd123
security:
  ignore-urls:
    - /rest/data/ignore
    - /rpc/**/*
  #acl-mappings:
    #https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-Configuration-Binding
    #"[/rest/company/**/*]": "hasAnyRole('ROLE_COMPANY_USER','ROLE_COMPANY_ADMIN') or #oauth2.isClient()"
    #"[/rest/**/*]": "hasAnyRole('ROLE_COMPANY_USER') or #oauth2.isClient()"
  oauth2:
    client:
      client-id: entdiy-mdm
      client-secret: 123456