spring:
  profiles:
    active: local
    include: config, jpa
  datasource:
    # 设置P6Spy驱动，以获得SQL打印监控功能
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://${params.spring.datasource.host}:${params.spring.datasource.port}/entdiy_mdm?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: entdiy_mdm
    password: entdiy_mdm_P@ssword123
  jpa:
    database-platform: com.entdiy.jpa.TenantMySQL57Dialect
    hibernate:
      ddlAuto: update
    properties:
      hibernate:
        storage_engine: innodb
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        new_generator_mappings: false
        format_sql: true
        show_sql: true
mybatis-plus:
  generator:
    author: Li Xia
    parentPackageName: com.entdiy
    moduleName: mdm
    tablePrefix: mdm_
    superClassStrategy: com.entdiy.mybatisplus.generator.FieldParseSuperClassStrategy
