server:
  port: 8080
  servlet:
    context-path: /api
    encoding:
      enabled: true
      force: true
      charset: UTF-8
  tomcat:
    uri-encoding: UTF-8
spring:
  main:
    allow-bean-definition-overriding: true
  mvc:
    throw-exception-if-no-handler-found: true
  jackson:
    mapper:
      default-view-inclusion: true
    serialization:
      #格式化输出
      indent_output: true
    #设置空如何序列化
    defaultPropertyInclusion: NON_NULL
    deserialization:
      #允许对象忽略json中不存在的属性
      fail_on_unknown_properties: false
  security:
    user:
      name: root
      password: rootUserP@ssword123
      role: ADMIN
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # CREATE DATABASE IF NOT EXISTS  entdiy default character set utf8mb4 collate utf8mb4_unicode_ci;
    url: jdbc:mysql://127.0.0.1:3306/entdiy_biz?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: mysqlP@ssword123
    druid:
      # 连接池配置
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 10000
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      validation-query: SELECT 1 FROM DUAL
      validation-query-timeout: 5000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      max-evictable-idle-time-millis: 60000
      removeAbandoned: false
      removeAbandonedTimeout: 1800
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控服务器
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: druidP@assword123
        reset-enable: false
        url-pattern: /druid/*
        # 添加IP白名单
        #allow:
        # 添加IP黑名单，当白名单和黑名单重复时，黑名单优先级更高
        #deny:
      web-stat-filter:
        enabled: true
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤格式
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      # 单个写法灵活各个控制
      filter:
        stat:
          enabled: true
          slowSqlMillis: 5000
        slf4j:
          enabled: true
          # 特别注意：有些控制参数后缀是Enable，有些是Enabled，特别坑！！！
          statementExecutableSqlLogEnable: true
          connectionLogEnabled: false
          resultSetLogEnabled: false
          statementCreateAfterLogEnabled: false
          statementPrepareAfterLogEnabled: false
          statementPrepareCallAfterLogEnabled: false
          statementExecuteAfterLogEnabled: false
          statementExecuteQueryAfterLogEnabled: false
          statementExecuteUpdateAfterLogEnabled: false
          statementExecuteBatchAfterLogEnabled: false
          statementCloseAfterLogEnabled: false
          statementParameterClearLogEnable: false
          statementParameterSetLogEnabled: false
        wall:
          enabled: false
          config:
            # 兼容Flyway配置
            comment-allow: true
  redis:
    host: 127.0.0.1
    port: 6379
    password: redisP@ssword123
    database: 0
    lettuce:
      pool:
        # 最大活跃链接数 默认8
        max-active: 5
        # 最大空闲连接数 默认8
        max-idle: 10
        # 最小空闲连接数 默认0
        min-idle: 0
security:
  oauth2:
    client:
      client-id: test
      client-secret: test123
      authorization-host-uri: http://localhost:8080/auth
      user-authorization-uri: ${security.oauth2.client.authorization-host-uri}/oauth/authorize
      access-token-uri: ${security.oauth2.client.authorization-host-uri}/oauth/token
    resource:
      jwt:
        key-value: jwtSigning@prd123
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 'null' #逻辑已删除值(默认为 1)，null字符串mybatis-plus会转换为null处理
      logic-not-delete-value: 0 #逻辑未删除值(默认为 0)
      update-strategy: ignored  #忽略动态更新，始终更新所有字段
    banner: false
  mapper-locations: classpath*:/com/entdiy/**/*.xml
  typeEnumsPackage: com.entdiy
  configuration:
    cache-enabled: false
logging:
  config: classpath:logback-spring-prd.xml
app:
  demoMode: false
  devMode: false
  systemName: "EntDIY Master Data Management"
  security:
    # 确保生产环境不同于任何开发或测试等环境配置，否则会导致其他环境的永不过期的JWT被恶意放到生产环境使用
    jwtSigningKey: jwtSigning@prd123
    ignore-urls:
      - /rest/data/ignore
      - /rpc/**/*
    oauth2:
      client:
        client-id: entdiy-mdm
        client-secret: test123
        access-token-uri: http://localhost:8080/auth/oauth/token
