server:
  port: 9101
monitor:
  #需要监控的服务名spring.application.name
  applications:
    - entdiy-system
    - entdiy-job
    - entdiy-gen
  #监控页面的登录用户名和密码
  login-username: admin
  login-password: 123456
logging:
  level:
    ROOT: INFO
