server:
  port: 8080
spring:
  profiles:
    include: local
  cloud:
    nacos:
      discovery:
        # 本地开发环境设定特定的服务注册名称，避免干扰共享环境服务列表
        service: dev-${spring.application.name}
logging:
  config: classpath:logback-spring-dev.xml
  level:
    com.entdiy: debug
app:
  devMode: true
  security:
    # 确保生产环境不同于任何开发或测试等环境配置，否则会导致其他环境的永不过期的JWT被恶意放到生产环境使用
    jwtSigningKey: jwtSigning@123
