server:
  port: -1
spring:
  application:
    name: service-mdm
  profiles:
    include: generator,local
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/entdiy_biz?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: mysqlP@ssword123
mybatis-plus:
  generator:
    author: Li Xia
    parentPackageName: com.entdiy
    moduleName: mdm
    tablePrefix: sys_,auth_
logging:
  level:
    com.entdiy: DEBUG
