version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    hostname: mysql-server
    environment:
      TZ: 'Asia/Shanghai'
      MYSQL_ROOT_PASSWORD: mysqlP@ssword123
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ../sql:/docker-entrypoint-initdb.d
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci'
    ]
    restart: on-failure:3
  redis:
    image: redis:5
    container_name: redis
    hostname: redis-server
    environment:
      TZ: 'Asia/Shanghai'
    ports:
      - 6379:6379
    command: --requirepass redisP@ssword123
    restart: on-failure:3
