spring:
  jpa:
    database-platform: com.entdiy.jpa.TenantMySQL57Dialect
    hibernate:
      ddlAuto: update
    properties:
      hibernate:
        storage_engine: innodb
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        new_generator_mappings: false
        format_sql: true
        show_sql: true