server:
  port: 9500

spring:
  datasource:
    dynamic:
      datasource:
        master:
          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
          url: jdbc:p6spy:mysql://${MYSQL_SERVER_HOST:127.0.0.1}:3306/entdiy_allinone?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
          username: entdiy
          password: entdiyP@ssword123
  cloud:
    sentinel:
      log:
        dir: ${APP_LOG_FOLDER:./log}/${spring.application.name}

# 本地文件上传
file:
  domain: http://127.0.0.1:9300
  path: D:/entdiy/uploadPath
  prefix: /statics

# FastDFS配置
#fdfs:
#  domain: http://8.129.231.12
#  soTimeout: 3000
#  connectTimeout: 2000
#  trackerList: 8.129.231.12:22122

# Minio配置
#minio:
#  url: http://8.129.231.12:9000
#  accessKey: minioadmin
#  secretKey: minioadmin
#  bucketName: test

