server:
  port: 8080
spring:
  cloud:
    sentinel:
      # 开发环境不启用，其余环境启用基于Nacos配置的限流控制
      enabled: true
      # 取消控制台懒加载
      eager: true
      transport:
        # 控制台地址
        dashboard: 127.0.0.1:8718
      # nacos配置持久化
      datasource:
        ds1:
          nacos:
            server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
            dataId: entdiy-gateway-sentinel.json
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        # 认证中心
        - id: entdiy-auth
          #uri: lb://entdiy-auth
          uri: http://127.0.0.1:9204
          predicates:
            - Path=/auth/**
          filters:
            # 验证码处理
            - CacheRequestFilter
            - ValidateCodeFilter
            - StripPrefix=1
        # 代码生成
        - id: entdiy-gen
          #uri: lb://entdiy-gen
          uri: http://127.0.0.1:9202
          predicates:
            - Path=/code/**
          filters:
            - StripPrefix=1
        # 定时任务
        - id: entdiy-job
          #uri: lb://entdiy-job
          uri: http://127.0.0.1:9203
          predicates:
            - Path=/schedule/**
          filters:
            - StripPrefix=1
        # 系统模块
        - id: entdiy-system
          #uri: lb://entdiy-system
          uri: http://127.0.0.1:9201
          predicates:
            - Path=/system/**
          filters:
            - StripPrefix=1
        # 文件服务
        - id: entdiy-file
          #uri: lb://entdiy-file
          uri: http://127.0.0.1:9300
          predicates:
            - Path=/file/**
          filters:
            - StripPrefix=1
        # Boot Admin 监控
        - id: entdiy-monitor
          #uri: lb://entdiy-monitor
          uri: http://127.0.0.1:9100
          predicates:
            - Path=/monitor/**
        # Druid SQL 监控
        - id: entdiy-druid
          #uri: lb://entdiy-druid
          uri: http://127.0.0.1:9101
          predicates:
            - Path=/druid/**
# 不校验白名单
ignore:
  whites:
    - /*/pub/**
    - /monitor/**
    - /druid/**
    - /docs/**
    - /auth/logout
    - /auth/login
    - /*/v2/api-docs
    - /csrf

